---
title: "R Notebook ejercicio"
output:
  html_document:
    df_print: paged
---

```{r setup, include=TRUE}
knitr::opts_chunk$set(echo = TRUE, error = TRUE)
library(assertthat)
library(testthat)
```

Leer el archivo CSV

```{r}
source('main.R')

data_wineR <- read.csv(FILE_OUTPUT, sep = ',')
dim(data_wineR)
View(data_wineR)
hist(data_wineR)
boxplot(data_wineR$Alcohol, horizontal=TRUE, main="Valores de alcohol")

library(ggplot2)
ggplot(data_wineR, aes(x=as.factor(class), y=Alcohol)) + geom_boxplot(fill="slateblue", alpha=0.2)
# Se ve cómo están distribuidos los datos

count(data_wineR, 'gear')

```

Quitar NA y otros

```{r}
data_wineR2 <- na.omit(data_wineR)
ggplot(data_wineR2, aes(x=as.factor(class), y=Alcohol)) + geom_boxplot(fill="slateblue", alpha=0.2)
# No hay NA, así que no tiene mucho sentido, sale lo mismo
summary(c(data_wineR2$Alcohol, data_wineR2$class))

```

Contar las clases
```{r}
library(dplyr)
data_wineR2$class <- as.factor(data_wineR2$class)
#Lo convierto 
data_wineR2 %>% count(class)
data_wineR2 %>% group_by(class ) %>% count()

#Quitar primera columna que no vale
data_wineR2 <- select(data_wineR2, -X)
View(data_wineR2)
```


```{r}
# Agrupar el dataset por clases y de esas filtrar cuáles tienen más de 13 grados de alcohol y lo muestro en gráfico
data_wineR2 %>% filter(Alcohol > 13) %>% group_by(class) %>% count() %>% 
  ggplot(aes(x=class, y=n)) + geom_bar(stat="identity", fill="steelblue")

View(data_wineR2)

```
